### PR TITLE
Alpha 1

### PR DESCRIPTION
**Pull request by SoundGoddess**
Game should be stable and but there are many GUI glitches that make it a bit unplayable.

### CODE REVIEW

**Comment by craftworkgames** [comment]
@SoundGoddess Hey I'm really impressed by what you've done with this and the Ruge project.

I just thought I'd let you know I got inspired by this project to [make a demo](https://github.com/craftworkgames/MonoGame.Extended/tree/game-solitare/Source/Demos/Demo.Solitare) for MonoGame.Extended. I've been working on it on and off over the past couple of weeks between other things.

image

It's not as playable as your's yet but I've been using it to make improvements to Extended as I go. I figured you might be able to borrow some of the code or whatever.

To be honest, I poked around the OpenSolitare code for a while trying to help but I had a hard time understanding how it was supposed to work. It looks like you've cleaned it up a lot in this PR which is great.

I noticed you borrowed some of the classes out of Extended. Thanks for giving credit in the text file, if you could add a URL that'd be great.

**Comment by SoundGoddess** [comment]
oh nice, I didn't know you were working on one too.  I'll check out your code.  :)

I added a link to your website in the attribution file.  

Ruge Project is more about me trying to learn MonoGame and share my insights and tutorials with the community rather than a serious project in its own right.  It's kind of tongue-in-cheek really.  But it's helping me figure out the workflow of managing an open source project, and giving me somewhere to dump code so I can share it easily.

Honestly, if I can work out the bugs and my code is up to snuff I'm perfectly happy to contribute anything from Ruge into a larger community project like Extended.  I did try the resharper tool, but it made visual studio really sluggish so I uninstalled it for the time being.  I figure I'll revisit it once Ruge is a bit more mature, since i'll qualify again with JetBrains for the open-source licensing.

**Comment by SoundGoddess** [comment]
oops I meant to tag you @craftworkgames :)

**Comment by craftworkgames** [comment]
> But it's helping me figure out the workflow of managing an open source project

Yeah I think what you're doing is a great way to go. I've learned a lot by running a few open source projects over the years. 

> I did try the resharper tool, but it made visual studio really sluggish so I uninstalled it for the time being.

I have heard people say that before. I guess it needs a beefy computer to run it on. Although, I do run it on my laptop as well and it's okay. To be honest I don't think I could work without it these days.

**Pull request merged**
